version: '3.8'

services:
  sls:
    build:
      context: .
      dockerfile: Dockerfile
#    command: >
#      sh -c "dotnet build"
    ports:
      - 1111:1111
    volumes:
      - ./:/SlSCarsServerStub
    depends_on:
      - db

  db:
    container_name: mssql_db
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - ./db:/var/opt/mssql/data


volumes:
  db:
